export const VUEX_APPEND_NEW_OHLC                               = 'VUEX_APPEND_NEW_OHLC'
export const VUEX_SET_HISTORICAL_OHLC                           = 'VUEX_SET_HISTORICAL_OHLC'

// GET REQUESTS
export const VUEX_GET_REQUEST_OHLC                              = 'VUEX_GET_REQUEST_OHLC'
export const VUEX_GET_REQUEST_OHLC_SUCCESS                      = 'VUEX_GET_REQUEST_OHLC_SUCCESS'
export const VUEX_GET_REQUEST_OHLC_FAILURE                      = 'VUEX_GET_REQUEST_OHLC_FAILURE'
export const VUEX_SET_LIQUIDATION_ZONES                         = 'VUEX_SET_LIQUIDATION_ZONES'


//VOLUME 
export const VUEX_SET_LIQUIDATION_VOLUME                        = 'VUEX_SET_LIQUIDATION_VOLUME'
export const VUEX_INCREMENT_LIQUIDATION_VOLUME                  = 'VUEX_INCREMENT_LIQUIDATION_VOLUME'
export const VUEX_DECREMENT_LIQUIDATION_VOLUME                  = 'VUEX_DECREMENT_LIQUIDATION_VOLUME'

//TIME INTERVAL
export const VUEX_SET_LIQUIDATION_TIMEINTERVAL                  = 'VUEX_SET_LIQUIDATION_TIMEINTERVAL'
export const VUEX_INCREMENT_LIQUIDATION_TIMEINTERVAL            = 'VUEX_INCREMENT_LIQUIDATION_TIMEINTERVAL'
export const VUEX_DECREMENT_LIQUIDATION_TIMEINTERVAL            = 'VUEX_DECREMENT_LIQUIDATION_TIMEINTERVAL'

// LEVERAGES
export const VUEX_SET_LIQUIDATION_LEVERAGE                      = 'VUEX_SET_LIQUIDATION_LEVERAGE'
export const VUEX_INCREMENT_LIQUIDATION_LEVERAGE                = 'VUEX_INCREMENT_LIQUIDATION_LEVERAGE'
export const VUEX_DECREMENT_LIQUIDATION_LEVERAGE                = 'VUEX_DECREMENT_LIQUIDATION_LEVERAGE'


// SIMPLE AVERAGES REQUESTS
export const VUEX_GET_REQUEST_LIQUIDATIONS                      = 'VUEX_GET_REQUEST_LIQUIDATIONS'
export const VUEX_GET_REQUEST_LIQUIDATIONS_SUCCESS              = 'VUEX_GET_REQUEST_LIQUIDATIONS_SUCCESS'
export const VUEX_GET_REQUEST_LIQUIDATIONS_FAILURE              = 'VUEX_GET_REQUEST_LIQUIDATIONS_FAILURE'

// APPLY CONFIGS
export const VUEX_SET_APPLY_LIQUIDATIONS_OPTIONS                = "VUEX_SET_APPLY_LIQUIDATIONS_OPTIONS"

// SET SIMPLE AVERAGE POINTS
export const VUEX_SET_SIMPLE_AVERAGE_POINTS                     = "VUEX_SET_SIMPLE_AVERAGE_POINTS"

// SAVE LIQUIDATION OPTS
export const VUEX_SAVE_LIQUIDATION_OPTS                         = 'VUEX_SAVE_LIQUIDATION_OPTS'

// GET USER SETTINGS
export const VUEX_GET_USER_SETTINGS                             = "VUEX_GET_USER_SETTINGS"

//SET USER SETTINGS
export const VUEX_SET_USER_SETTINGS                             = "VUEX_SET_USER_SETTINGS"

//GET LIQUIDATION BUBBLES                                       
export const VUEX_GET_LIQUIDATION_BUBBLES                       = "VUEX_GET_LIQUIDATION_BUBBLES"
export const VUEX_GET_LIQUIDATION_BUBBLES_SUCCESS               = "VUEX_GET_LIQUIDATION_BUBBLES_SUCCESS"
export const VUEX_GET_LIQUIDATION_BUBBLES_FAILURE               = "VUEX_GET_LIQUIDATION_BUBBLES_FAILURE"

//SET LIQUIDATION BUBBLES
export const VUEX_SET_LIQUIDATION_BUBBLES                       = "VUEX_SET_LIQUIDATION_BUBBLES"

//SET DEFAULT LIQUIDATION CHART
export const VUEX_SET_DEFAULT_LIQUIDATIONS                      = "VUEX_SET_DEFAULT_LIQUIDATIONS"


//LIQUIDATION CHART DEFAULTS
export const VUEX_LIQUIDATION_LEVERAGE                          = "VUEX_LIQUIDATION_LEVERAGE"
export const VUEX_DEFAULT_LIQUIDATION_VOLUME                    = "5M"
export const VUEX_DEFAULT_LIQUIDATION_INTERVAL                  = "4H"
export const VUEX_LONG                                          = "LONG"
export const VUEX_SHORT                                         = "SHORT"

export const VUEX_LEVERAGES_LONG                                = "VUEX_LEVERAGES_LONG"
export const VUEX_LEVERAGES_SHORT                               = "VUEX_LEVERAGES_SHORT"

// CLEAR ALL LIQUIDATION LINES
export const VUEX_CLEAR_ALL_LIQUIDATIONS                        = "VUEX_CLEAR_ALL_LIQUIDATIONS"

// ADD CUSTOM LIQUIDATION LINES
export const VUEX_ADD_CUSTOM_LIQUIDATION_LINES                  = "VUEX_ADD_CUSTOM_LIQUIDATION_LINES"
export const VUEX_UPDATE_MATCHED_SERIES                         = "VUEX_UPDATE_MATCHED_SERIES"
export const VUEX_CLEAR_CHART_SERIES                            = "VUEX_CLEAR_CHART_SERIES"


// TOGGLE CROSSHAIR
export const VUEX_TOGGLE_CROSSHAIR                              = "VUEX_TOGGLE_CROSSHAIR"

// UNDO LAST MAGIC LINE
export const VUEX_UNDO_MAGIC_LINE                               = "VUEX_UNDO_MAGIC_LINE"

// UPDATE MAGIC LINES
export const VUEX_UPDATE_MAGIC_LINES                            = "VUEX_UPDATE_MAGIC_LINES"
export const VUEX_UPDATE_MAGIC_LINES_SUCCESS                    = "VUEX_UPDATE_MAGIC_LINES_SUCCESS"
export const VUEX_UPDATE_MAGIC_LINES_FAILURE                    = "VUEX_UPDATE_MAGIC_LINES_FAILURE"

// UPDATE FROM LOCALSTORAGE
export const VUEX_UPDATE_FROM_LOCAL_STORAGE                     = "VUEX_UPDATE_FROM_LOCAL_STORAGE"
export const VUEX_GET_REQUEST_LIQUIDATIONS_PROMISE              = "VUEX_GET_REQUEST_LIQUIDATIONS_PROMISE"
export const VUEX_FORCE_CHART_RENDER                            = "VUEX_FORCE_CHART_RENDER"

//SET PRESETS
export const VUEX_SET_MAGIC_PRESETS                             = "VUEX_SET_MAGIC_PRESETS"

// CREATE PRESET NAME BASED ON CURRENT LIQUIDATIONS 
export const VUEX_CREATE_PRESET_NAME                            = "VUEX_CREATE_PRESET_NAME"

//SAVE PRESETS
export const VUEX_SAVE_PRESETS                                  = "VUEX_SAVE_PRESETS"

// DELETE PRESET
export const VUEX_DELETE_PRESETS                                = "VUEX_DELETE_PRESETS"

// GET PRESETS
export const VUEX_GET_PRESETS                                   = "VUEX_GET_PRESETS"

// RENAME PRESET
export const VUEX_RENAME_PRESET                                 = "VUEX_RENAME_PRESET"


//LOAD PRESET
export const VUEX_LOAD_PRESET                                   = "VUEX_LOAD_PRESET"